### ISSUE TITLE
Pom 的依赖地址无法使用，无法安装依赖

### ISSUE THREAD

**Issue by cybrobin** [hejiehui/xDecision#3]
Could not find artifact com.xrosstools:xdecision:pom:2.3.0-SNAPSHOT in xtools-repo (https://raw.github.com/hejiehui/xtools-repo/mvn-repo/)

**Comment by minosniu** [comment]
我也有这个问题，请问一下作者怎么解决？

**Comment by hejiehui** [comment]
已经发布到maven中央仓库：
https://s01.oss.sonatype.org/#nexus-search;quick~xdecision
