### ISSUE TITLE
操作符运算可采用 AviatorEvaluator 规则引擎，性能会更高吧

### ISSUE THREAD

**Issue by cybrobin** [hejiehui/xDecision#4]
操作符运算可采用 AviatorEvaluator 规则引擎，性能会更高吧
com.googlecode.aviator.AviatorEvaluator

**Comment by hejiehui** [comment]
已经基于AviatorEvaluator提供了com.xrosstools.xdecision.ext.AviatorPathEvaluator
为了避免引入不必要的依赖，目前定义的scope是provided，如果你需要使用，可以自行增加依赖
        <dependency>
            <groupId>com.googlecode.aviator</groupId>
            <artifactId>aviator</artifactId>
            <version>${aviator-version}</version>
            <scope>provided</scope>
        </dependency>
